### ISSUE TITLE
Mail configuration

### ISSUE THREAD

**Issue by raphaelcasimir** [tiagoboldt/sharelatex-docker#23]
Hello, can you indicate me where the (mail) settings file is ? If it is in /sharelatex/web/config, when I uncomment the mail parameter, it can't restart (the container shuts down after a few seconds).
If it is in /sharelatex/config it just doesn't do anything (after a restart, and yes, the file is persistent).
It needs to be in production tomorow, so I hope you can help.

Thanks by advance

**Comment by DirkHeinke** [comment]
The used config file is in `/etc/sharelatex/settings.coffee`

**Comment by raphaelcasimir** [comment]
Thanks a lot.
It was simple, but I didn't see it was a directory...
From now on I'm going full "la", no more simple ls.
You rock.

**Comment by raphaelcasimir** [comment]
But the container still doesn't live more than 7 seconds when I do a modification and restart. Maybe you will see something:
        email:
                fromAddress: "mail@domain.com"
                replyTo: "mail@domain.com"
                transport: "SMTP"
                parameters:
                        host: "smtp.gmail.com"
                        port: "465"
                        # Authentication
                        authMethod: "PLAIN"
                        auth: {
                                user: 'noreply.openrobotics@gmail.com',
                                pass: 'my_password'
                              }
			secure: true

**Comment by DirkHeinke** [comment]
Anything in the logs in `/data/logs/`?

**Comment by raphaelcasimir** [comment]
In web.lo the last error i'm getting is

/sharelatex/web/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:82
      throw err;
            ^
Error: In /etc/sharelatex/settings.coffee, Parse error on line 140: Unexpected '{'
    at Object.parseError (/sharelatex/web/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/parser.js:483:11)
    at Object.parse (/sharelatex/web/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/parser.js:535:22)
    at exports.compile.compile (/sharelatex/web/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:60:27)
    at Object.loadFile (/sharelatex/web/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:28)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/sharelatex/web/node_modules/settings-sharelatex/Settings.coffee:42:30)
    at Object.<anonymous> (/sharelatex/web/node_modules/settings-sharelatex/Settings.coffee:54:4)
    at Module._compile (module.js:456:26)
    at Object.loadFile (/sharelatex/web/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/sharelatex/web/node_modules/settings-sharelatex/index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/sharelatex/web/app.js:4:14)
    at Object.<anonymous> (/sharelatex/web/app.js:73:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by raphaelcasimir** [comment]
Ok I just did a tail -f on web.log and redid the operation I'm sure this is this error that crashes everything.

**Comment by DirkHeinke** [comment]
I don't really know how the parser works, but the error says, that the { is wrong. Try without the {} in the auth block and use indenting instead.

**Comment by raphaelcasimir** [comment]
Let's do this

**Comment by raphaelcasimir** [comment]
Line 140 is the one just before email, just tried to remove the {} but exactly the same error

**Comment by tiagoboldt** [comment]
Can you post the exact file you're using? Not sure, but indentation might be relevant here.

**Comment by raphaelcasimir** [comment]
let me try something

**Comment by raphaelcasimir** [comment]
Ok, the indentation WAS important. Though they do not put it right on the sharelatex github (or github translate it badly) : working file here -> [settings.coffee](http://pastebin.com/02F8yHmE)

**Comment by tiagoboldt** [comment]
@raphaelcasimir the file you've posted had your password in it. Consider changing the password in the email now, and wherever you're using it also.

**Comment by raphaelcasimir** [comment]
Just saw it... Modified :grin:

**Comment by raphaelcasimir** [comment]
A last question, I need to send the emails from my local host machine (restrictive mail rules inside the network). I use the mail command on the host, and it works fine, but is it possible to do it from the sharelatex container and how ? What is the "transport" setting ? I have already searched but not found...

**Comment by tiagoboldt** [comment]
From the docs: "ShareLaTeX only supports SMTP as transports". My approach would be to install a local SMTP server and configure sharelatex to use it.
